import { createId } from "../id";
import type { CanvasElement, ProjectDocument } from "../types";

function baseMeta(name: string): ProjectDocument["meta"] {
  const now = new Date().toISOString();
  return {
    id: createId("proj"),
    name,
    createdAt: now,
    updatedAt: now,
    version: 1,
  };
}

/** Procedural ink-wash SVG data URL used as local image assets in templates. */
export function inkWashDataUrl(
  w: number,
  h: number,
  ink = "#9FE870",
  paper = "#1a211c"
): string {
  // Flat plate only — no radial/mesh gradients (Brandon bar)
  const svg = `<svg xmlns="http://www.w3.org/2000/svg" width="${w}" height="${h}" viewBox="0 0 ${w} ${h}">
  <rect width="100%" height="100%" fill="${paper}"/>
  <rect x="0" y="${Math.floor(h * 0.72)}" width="100%" height="${Math.floor(h * 0.28)}" fill="${ink}" opacity="0.22"/>
</svg>`;
  return `data:image/svg+xml;charset=utf-8,${encodeURIComponent(svg)}`;
}

function igSquare(name: string, elements: CanvasElement[], bg: string): ProjectDocument {
  return {
    meta: baseMeta(name),
    canvas: { width: 1080, height: 1080, label: "Instagram Post" },
    elements,
    layerOrder: elements.map((e) => e.id),
    background: bg,
  };
}

export function createEmptyProject(
  size: { width: number; height: number; label: string } = {
    width: 1080,
    height: 1080,
    label: "Instagram Post",
  }
): ProjectDocument {
  return {
    meta: baseMeta("Untitled graphic"),
    canvas: size,
    elements: [],
    layerOrder: [],
    background: "#121612",
  };
}

export const CANVAS_PRESETS = [
  { width: 1080, height: 1080, label: "Instagram Post" },
  { width: 1080, height: 1920, label: "Instagram Story" },
  { width: 1200, height: 627, label: "LinkedIn / OG" },
  { width: 1500, height: 500, label: "X Header" },
  { width: 1080, height: 1350, label: "Portrait Post" },
] as const;

export type StarterId =
  | "launch-poster"
  | "quote-card"
  | "story-countdown"
  | "event-flyer"
  | "product-drop"
  | "shop-hours"
  | "story-offer";

export interface StarterTemplate {
  id: StarterId;
  name: string;
  blurb: string;
  category: string;
  /** Preview overlay for gallery cards — real copy, not SAMPLE */
  previewHeadline: string;
  previewSub?: string;
  sizeLabel: string;
  build: () => ProjectDocument;
}

export const STARTER_TEMPLATES: StarterTemplate[] = [
  {
    id: "launch-poster",
    name: "Shop Open Poster",
    blurb: "Mesa diesel bay — charcoal sheet, lime strike, export-ready.",
    category: "Social",
    previewHeadline: "MESA BAY OPEN",
    previewSub: "Same-day · Apache Blvd",
    sizeLabel: "1080×1080",
    build: () => {
      const wash = "/assets/texture-square.jpg";
      const imgId = createId("el");
      const barId = createId("el");
      const titleId = createId("el");
      const subId = createId("el");
      const tagId = createId("el");
      const elements: CanvasElement[] = [
        {
          id: imgId,
          type: "image",
          name: "Ink wash",
          x: 0,
          y: 0,
          width: 1080,
          height: 1080,
          rotation: 0,
          opacity: 1,
          locked: false,
          visible: true,
          parentId: null,
          src: wash,
          objectFit: "cover",
        },
        {
          id: barId,
          type: "rect",
          name: "Strike bar",
          x: 72,
          y: 700,
          width: 220,
          height: 14,
          rotation: 0,
          opacity: 1,
          locked: false,
          visible: true,
          parentId: null,
          fill: "#9FE870",
          stroke: "transparent",
          strokeWidth: 0,
          cornerRadius: 0,
        },
        {
          id: titleId,
          type: "text",
          name: "Headline",
          x: 72,
          y: 740,
          width: 920,
          height: 140,
          rotation: 0,
          opacity: 1,
          locked: false,
          visible: true,
          parentId: null,
          text: "MESA BAY OPEN",
          fontFamily: "Archivo Black",
          fontSize: 84,
          fontWeight: 400,
          fill: "#F4F7F2",
          align: "left",
          lineHeight: 1.05,
          letterSpacing: -2,
        },
        {
          id: subId,
          type: "text",
          name: "Subhead",
          x: 72,
          y: 900,
          width: 780,
          height: 60,
          rotation: 0,
          opacity: 1,
          locked: false,
          visible: true,
          parentId: null,
          text: "AZ Mobile Diesel · Apache Blvd · same-day",
          fontFamily: "IBM Plex Mono",
          fontSize: 26,
          fontWeight: 500,
          fill: "#E8A54B",
          align: "left",
          lineHeight: 1.2,
          letterSpacing: 0.5,
        },
        {
          id: tagId,
          type: "text",
          name: "Corner mark",
          x: 72,
          y: 64,
          width: 480,
          height: 40,
          rotation: 0,
          opacity: 1,
          locked: false,
          visible: true,
          parentId: null,
          text: "FORGE / MESA 09",
          fontFamily: "IBM Plex Mono",
          fontSize: 22,
          fontWeight: 500,
          fill: "#9FE870",
          align: "left",
          lineHeight: 1.2,
          letterSpacing: 4,
        },
      ];
      return igSquare("Mesa Bay Open — IG", elements, "#141a15");
    },
  },
  {
    id: "quote-card",
    name: "Bay Quote",
    blurb: "Pull-quote for the shop wall — amber rule, editorial type.",
    category: "Social",
    previewHeadline: "“Fix it once.",
    previewSub: "— R. Castillo, Mesa",
    sizeLabel: "1080×1080",
    build: () => {
      const ruleId = createId("el");
      const quoteId = createId("el");
      const attrId = createId("el");
      const frameId = createId("el");
      const elements: CanvasElement[] = [
        {
          id: frameId,
          type: "rect",
          name: "Frame",
          x: 48,
          y: 48,
          width: 984,
          height: 984,
          rotation: 0,
          opacity: 1,
          locked: false,
          visible: true,
          parentId: null,
          fill: "transparent",
          stroke: "#2a332c",
          strokeWidth: 3,
          cornerRadius: 0,
        },
        {
          id: ruleId,
          type: "rect",
          name: "Amber rule",
          x: 120,
          y: 280,
          width: 96,
          height: 8,
          rotation: 0,
          opacity: 1,
          locked: false,
          visible: true,
          parentId: null,
          fill: "#E8A54B",
          stroke: "transparent",
          strokeWidth: 0,
          cornerRadius: 0,
        },
        {
          id: quoteId,
          type: "text",
          name: "Quote",
          x: 120,
          y: 320,
          width: 840,
          height: 420,
          rotation: 0,
          opacity: 1,
          locked: false,
          visible: true,
          parentId: null,
          text: "“Fix it once on the lot — not twice in the shop.”",
          fontFamily: "Playfair Display",
          fontSize: 58,
          fontWeight: 700,
          fill: "#F4F7F2",
          align: "left",
          lineHeight: 1.25,
          letterSpacing: -0.5,
        },
        {
          id: attrId,
          type: "text",
          name: "Attribution",
          x: 120,
          y: 820,
          width: 700,
          height: 48,
          rotation: 0,
          opacity: 1,
          locked: false,
          visible: true,
          parentId: null,
          text: "— R. Castillo · Mesa diesel tech",
          fontFamily: "IBM Plex Sans",
          fontSize: 28,
          fontWeight: 500,
          fill: "#8a948c",
          align: "left",
          lineHeight: 1.2,
          letterSpacing: 0,
        },
      ];
      return igSquare("Bay Quote — IG", elements, "#0f1310");
    },
  },
  {
    id: "story-countdown",
    name: "Market Countdown",
    blurb: "Vertical story — big number, Roosevelt Row night market.",
    category: "Story",
    previewHeadline: "03",
    previewSub: "DAYS · ROOSEVELT ROW",
    sizeLabel: "1080×1920",
    build: () => {
      const now = new Date().toISOString();
      const circleId = createId("el");
      const numId = createId("el");
      const labelId = createId("el");
      const ctaId = createId("el");
      const placeId = createId("el");
      const elements: CanvasElement[] = [
        {
          id: circleId,
          type: "circle",
          name: "Glow disc",
          x: 190,
          y: 520,
          width: 700,
          height: 700,
          rotation: 0,
          opacity: 0.2,
          locked: false,
          visible: true,
          parentId: null,
          fill: "#9FE870",
          stroke: "transparent",
          strokeWidth: 0,
        },
        {
          id: numId,
          type: "text",
          name: "Countdown",
          x: 80,
          y: 640,
          width: 920,
          height: 280,
          rotation: 0,
          opacity: 1,
          locked: false,
          visible: true,
          parentId: null,
          text: "03",
          fontFamily: "Archivo Black",
          fontSize: 280,
          fontWeight: 400,
          fill: "#F4F7F2",
          align: "center",
          lineHeight: 0.9,
          letterSpacing: -8,
        },
        {
          id: labelId,
          type: "text",
          name: "Label",
          x: 80,
          y: 960,
          width: 920,
          height: 60,
          rotation: 0,
          opacity: 1,
          locked: false,
          visible: true,
          parentId: null,
          text: "DAYS TO NIGHT MARKET",
          fontFamily: "IBM Plex Mono",
          fontSize: 30,
          fontWeight: 600,
          fill: "#9FE870",
          align: "center",
          lineHeight: 1.2,
          letterSpacing: 5,
        },
        {
          id: placeId,
          type: "text",
          name: "Place",
          x: 80,
          y: 1040,
          width: 920,
          height: 48,
          rotation: 0,
          opacity: 1,
          locked: false,
          visible: true,
          parentId: null,
          text: "Roosevelt Row · Sat 7PM · free entry",
          fontFamily: "IBM Plex Sans",
          fontSize: 26,
          fontWeight: 500,
          fill: "#b8c0b6",
          align: "center",
          lineHeight: 1.2,
          letterSpacing: 0,
        },
        {
          id: ctaId,
          type: "text",
          name: "Top mark",
          x: 80,
          y: 160,
          width: 920,
          height: 80,
          rotation: 0,
          opacity: 1,
          locked: false,
          visible: true,
          parentId: null,
          text: "SAVE THE DATE",
          fontFamily: "Archivo Black",
          fontSize: 42,
          fontWeight: 700,
          fill: "#E8A54B",
          align: "center",
          lineHeight: 1.1,
          letterSpacing: 2,
        },
      ];
      return {
        meta: {
          id: createId("proj"),
          name: "Roosevelt Night Market — Story",
          createdAt: now,
          updatedAt: now,
          version: 1,
        },
        canvas: { width: 1080, height: 1920, label: "Instagram Story" },
        elements,
        layerOrder: elements.map((e) => e.id),
        background: "#0c0f0d",
      };
    },
  },
  {
    id: "event-flyer",
    name: "Night Market Flyer",
    blurb: "PHX night market — lime band, amber stamp, print-ish square.",
    category: "Print-ish",
    previewHeadline: "NIGHT\nMARKET",
    previewSub: "SAT 21 · ROOSEVELT",
    sizeLabel: "1080×1080",
    build: () => {
      const stampId = createId("el");
      const stampTextId = createId("el");
      const titleId = createId("el");
      const whenId = createId("el");
      const whereId = createId("el");
      const bandId = createId("el");
      const elements: CanvasElement[] = [
        {
          id: bandId,
          type: "rect",
          name: "Bottom band",
          x: 0,
          y: 860,
          width: 1080,
          height: 220,
          rotation: 0,
          opacity: 1,
          locked: false,
          visible: true,
          parentId: null,
          fill: "#9FE870",
          stroke: "transparent",
          strokeWidth: 0,
          cornerRadius: 0,
        },
        {
          id: stampId,
          type: "circle",
          name: "Stamp",
          x: 720,
          y: 80,
          width: 260,
          height: 260,
          rotation: -12,
          opacity: 1,
          locked: false,
          visible: true,
          parentId: null,
          fill: "transparent",
          stroke: "#E8A54B",
          strokeWidth: 8,
        },
        {
          id: stampTextId,
          type: "text",
          name: "Stamp text",
          x: 740,
          y: 175,
          width: 220,
          height: 80,
          rotation: -12,
          opacity: 1,
          locked: false,
          visible: true,
          parentId: null,
          text: "PHX\nFREE",
          fontFamily: "Archivo Black",
          fontSize: 36,
          fontWeight: 400,
          fill: "#E8A54B",
          align: "center",
          lineHeight: 1.05,
          letterSpacing: 2,
        },
        {
          id: titleId,
          type: "text",
          name: "Title",
          x: 64,
          y: 320,
          width: 900,
          height: 200,
          rotation: 0,
          opacity: 1,
          locked: false,
          visible: true,
          parentId: null,
          text: "NIGHT\nMARKET",
          fontFamily: "Archivo Black",
          fontSize: 110,
          fontWeight: 800,
          fill: "#F4F7F2",
          align: "left",
          lineHeight: 0.95,
          letterSpacing: -3,
        },
        {
          id: whenId,
          type: "text",
          name: "When",
          x: 64,
          y: 900,
          width: 500,
          height: 80,
          rotation: 0,
          opacity: 1,
          locked: false,
          visible: true,
          parentId: null,
          text: "SAT 21 · 7PM",
          fontFamily: "Archivo Black",
          fontSize: 42,
          fontWeight: 400,
          fill: "#0c0f0d",
          align: "left",
          lineHeight: 1.1,
          letterSpacing: 1,
        },
        {
          id: whereId,
          type: "text",
          name: "Where",
          x: 64,
          y: 970,
          width: 700,
          height: 50,
          rotation: 0,
          opacity: 1,
          locked: false,
          visible: true,
          parentId: null,
          text: "Roosevelt Row · free entry",
          fontFamily: "IBM Plex Sans",
          fontSize: 28,
          fontWeight: 600,
          fill: "#0c0f0d",
          align: "left",
          lineHeight: 1.2,
          letterSpacing: 0,
        },
      ];
      return igSquare("PHX Night Market Flyer", elements, "#161c18");
    },
  },
  {
    id: "product-drop",
    name: "Hours Drop",
    blurb: "LinkedIn / OG wide — new shop hours, book on the lot.",
    category: "Wide",
    previewHeadline: "New hours. Same bay.",
    previewSub: "Mon–Sat 7–6 · Mesa",
    sizeLabel: "1200×627",
    build: () => {
      const now = new Date().toISOString();
      const wash = "/assets/texture-wide.jpg";
      const imgId = createId("el");
      const titleId = createId("el");
      const subId = createId("el");
      const chipId = createId("el");
      const chipTextId = createId("el");
      const elements: CanvasElement[] = [
        {
          id: imgId,
          type: "image",
          name: "Backdrop",
          x: 0,
          y: 0,
          width: 1200,
          height: 627,
          rotation: 0,
          opacity: 1,
          locked: false,
          visible: true,
          parentId: null,
          src: wash,
          objectFit: "cover",
        },
        {
          id: chipId,
          type: "rect",
          name: "Chip",
          x: 64,
          y: 72,
          width: 180,
          height: 40,
          rotation: 0,
          opacity: 1,
          locked: false,
          visible: true,
          parentId: null,
          fill: "#9FE870",
          stroke: "transparent",
          strokeWidth: 0,
          cornerRadius: 2,
        },
        {
          id: chipTextId,
          type: "text",
          name: "Chip label",
          x: 76,
          y: 78,
          width: 160,
          height: 32,
          rotation: 0,
          opacity: 1,
          locked: false,
          visible: true,
          parentId: null,
          text: "HOURS 09",
          fontFamily: "IBM Plex Mono",
          fontSize: 18,
          fontWeight: 700,
          fill: "#0c0f0d",
          align: "left",
          lineHeight: 1.2,
          letterSpacing: 2,
        },
        {
          id: titleId,
          type: "text",
          name: "Title",
          x: 64,
          y: 220,
          width: 980,
          height: 120,
          rotation: 0,
          opacity: 1,
          locked: false,
          visible: true,
          parentId: null,
          text: "New hours. Same bay.",
          fontFamily: "Archivo Black",
          fontSize: 64,
          fontWeight: 700,
          fill: "#F4F7F2",
          align: "left",
          lineHeight: 1.1,
          letterSpacing: -1,
        },
        {
          id: subId,
          type: "text",
          name: "Sub",
          x: 64,
          y: 360,
          width: 900,
          height: 80,
          rotation: 0,
          opacity: 1,
          locked: false,
          visible: true,
          parentId: null,
          text: "AZ Mobile Diesel · Mon–Sat 7AM–6PM · book on the lot",
          fontFamily: "IBM Plex Sans",
          fontSize: 26,
          fontWeight: 400,
          fill: "#b8c0b6",
          align: "left",
          lineHeight: 1.3,
          letterSpacing: 0,
        },
      ];
      return {
        meta: {
          id: createId("proj"),
          name: "AZMDR Hours — LinkedIn",
          createdAt: now,
          updatedAt: now,
          version: 1,
        },
        canvas: { width: 1200, height: 627, label: "LinkedIn / OG" },
        elements,
        layerOrder: elements.map((e) => e.id),
        background: "#121812",
      };
    },
  },
  {
    id: "shop-hours",
    name: "Bay Hours Card",
    blurb: "Square hours card — Mon–Sat grid, Mesa address, export PDF.",
    category: "Social",
    previewHeadline: "BAY HOURS",
    previewSub: "2140 E Apache · Mesa",
    sizeLabel: "1080×1080",
    build: () => {
      const titleId = createId("el");
      const hoursId = createId("el");
      const addrId = createId("el");
      const ruleId = createId("el");
      const tagId = createId("el");
      const bandId = createId("el");
      const elements: CanvasElement[] = [
        {
          id: bandId,
          type: "rect",
          name: "Side band",
          x: 0,
          y: 0,
          width: 28,
          height: 1080,
          rotation: 0,
          opacity: 1,
          locked: false,
          visible: true,
          parentId: null,
          fill: "#9FE870",
          stroke: "transparent",
          strokeWidth: 0,
          cornerRadius: 0,
        },
        {
          id: tagId,
          type: "text",
          name: "Tag",
          x: 80,
          y: 80,
          width: 400,
          height: 36,
          rotation: 0,
          opacity: 1,
          locked: false,
          visible: true,
          parentId: null,
          text: "AZ MOBILE DIESEL",
          fontFamily: "IBM Plex Mono",
          fontSize: 20,
          fontWeight: 600,
          fill: "#9FE870",
          align: "left",
          lineHeight: 1.2,
          letterSpacing: 3,
        },
        {
          id: titleId,
          type: "text",
          name: "Headline",
          x: 80,
          y: 160,
          width: 880,
          height: 100,
          rotation: 0,
          opacity: 1,
          locked: false,
          visible: true,
          parentId: null,
          text: "BAY HOURS",
          fontFamily: "Archivo Black",
          fontSize: 88,
          fontWeight: 400,
          fill: "#F4F7F2",
          align: "left",
          lineHeight: 1.05,
          letterSpacing: -2,
        },
        {
          id: ruleId,
          type: "rect",
          name: "Rule",
          x: 80,
          y: 280,
          width: 160,
          height: 8,
          rotation: 0,
          opacity: 1,
          locked: false,
          visible: true,
          parentId: null,
          fill: "#E8A54B",
          stroke: "transparent",
          strokeWidth: 0,
          cornerRadius: 0,
        },
        {
          id: hoursId,
          type: "text",
          name: "Hours",
          x: 80,
          y: 340,
          width: 880,
          height: 420,
          rotation: 0,
          opacity: 1,
          locked: false,
          visible: true,
          parentId: null,
          text: "Mon–Fri   7:00 AM – 6:00 PM\nSaturday  7:00 AM – 2:00 PM\nSunday    Closed · on-call",
          fontFamily: "IBM Plex Mono",
          fontSize: 36,
          fontWeight: 500,
          fill: "#eceee9",
          align: "left",
          lineHeight: 1.55,
          letterSpacing: 0,
        },
        {
          id: addrId,
          type: "text",
          name: "Address",
          x: 80,
          y: 900,
          width: 880,
          height: 80,
          rotation: 0,
          opacity: 1,
          locked: false,
          visible: true,
          parentId: null,
          text: "2140 E Apache Blvd · Mesa AZ 85204\nCall ahead · mobile service valley-wide",
          fontFamily: "IBM Plex Sans",
          fontSize: 26,
          fontWeight: 500,
          fill: "#8b958d",
          align: "left",
          lineHeight: 1.35,
          letterSpacing: 0,
        },
      ];
      return igSquare("Bay Hours — Mesa", elements, "#121812");
    },
  },
  {
    id: "story-offer",
    name: "Lot Special Story",
    blurb: "IG Story offer — diagnostic special, Tempe / Mesa fleet.",
    category: "Story",
    previewHeadline: "$89",
    previewSub: "DIAGNOSTIC · THIS WEEK",
    sizeLabel: "1080×1920",
    build: () => {
      const now = new Date().toISOString();
      const priceId = createId("el");
      const labelId = createId("el");
      const detailId = createId("el");
      const topId = createId("el");
      const barId = createId("el");
      const elements: CanvasElement[] = [
        {
          id: topId,
          type: "text",
          name: "Top mark",
          x: 80,
          y: 180,
          width: 920,
          height: 60,
          rotation: 0,
          opacity: 1,
          locked: false,
          visible: true,
          parentId: null,
          text: "THIS WEEK ONLY",
          fontFamily: "IBM Plex Mono",
          fontSize: 28,
          fontWeight: 600,
          fill: "#E8A54B",
          align: "center",
          lineHeight: 1.2,
          letterSpacing: 6,
        },
        {
          id: priceId,
          type: "text",
          name: "Headline",
          x: 80,
          y: 620,
          width: 920,
          height: 280,
          rotation: 0,
          opacity: 1,
          locked: false,
          visible: true,
          parentId: null,
          text: "$89",
          fontFamily: "Archivo Black",
          fontSize: 220,
          fontWeight: 400,
          fill: "#F4F7F2",
          align: "center",
          lineHeight: 0.9,
          letterSpacing: -6,
        },
        {
          id: labelId,
          type: "text",
          name: "Label",
          x: 80,
          y: 920,
          width: 920,
          height: 80,
          rotation: 0,
          opacity: 1,
          locked: false,
          visible: true,
          parentId: null,
          text: "ON-SITE DIAGNOSTIC",
          fontFamily: "Archivo Black",
          fontSize: 42,
          fontWeight: 400,
          fill: "#9FE870",
          align: "center",
          lineHeight: 1.1,
          letterSpacing: 2,
        },
        {
          id: barId,
          type: "rect",
          name: "Bar",
          x: 390,
          y: 1020,
          width: 300,
          height: 10,
          rotation: 0,
          opacity: 1,
          locked: false,
          visible: true,
          parentId: null,
          fill: "#E8A54B",
          stroke: "transparent",
          strokeWidth: 0,
          cornerRadius: 0,
        },
        {
          id: detailId,
          type: "text",
          name: "Detail",
          x: 100,
          y: 1080,
          width: 880,
          height: 160,
          rotation: 0,
          opacity: 1,
          locked: false,
          visible: true,
          parentId: null,
          text: "Fleet vans · box trucks · light diesel\nTempe · Mesa · Chandler\nText the bay to book",
          fontFamily: "IBM Plex Sans",
          fontSize: 32,
          fontWeight: 500,
          fill: "#b8c0b6",
          align: "center",
          lineHeight: 1.4,
          letterSpacing: 0,
        },
      ];
      return {
        meta: {
          id: createId("proj"),
          name: "Diagnostic Special — Story",
          createdAt: now,
          updatedAt: now,
          version: 1,
        },
        canvas: { width: 1080, height: 1920, label: "Instagram Story" },
        elements,
        layerOrder: elements.map((e) => e.id),
        background: "#0e1210",
      };
    },
  },
];

export function getStarter(id: StarterId): StarterTemplate | undefined {
  return STARTER_TEMPLATES.find((t) => t.id === id);
}
